<?php

namespace Vision\Annotation;

class Type
{
    /**
     * @see https://cloud.google.com/vision/reference/rest/v1/images/annotate#Type_1
     */
    const UNKNOWN_LANDMARK = 'UNKNOWN_LANDMARK';
    const LEFT_EYE = 'LEFT_EYE';
    const RIGHT_EYE = 'RIGHT_EYE';
    const LEFT_OF_LEFT_EYEBROW = 'LEFT_OF_LEFT_EYEBROW';
    const RIGHT_OF_LEFT_EYEBROW = 'RIGHT_OF_LEFT_EYEBROW';
    const LEFT_OF_RIGHT_EYEBROW = 'LEFT_OF_RIGHT_EYEBROW';
    const RIGHT_OF_RIGHT_EYEBROW = 'RIGHT_OF_RIGHT_EYEBROW';
    const MIDPOINT_BETWEEN_EYES = 'MIDPOINT_BETWEEN_EYES';
    const NOSE_TIP = 'NOSE_TIP';
    const UPPER_LIP = 'UPPER_LIP';
    const LOWER_LIP = 'LOWER_LIP';
    const MOUTH_LEFT = 'MOUTH_LEFT';
    const MOUTH_RIGHT = 'MOUTH_RIGHT';
    const MOUTH_CENTER = 'MOUTH_CENTER';
    const NOSE_BOTTOM_RIGHT = 'NOSE_BOTTOM_RIGHT';
    const NOSE_BOTTOM_LEFT = 'NOSE_BOTTOM_LEFT';
    const NOSE_BOTTOM_CENTER = 'NOSE_BOTTOM_CENTER';
    const LEFT_EYE_TOP_BOUNDARY = 'LEFT_EYE_TOP_BOUNDARY';
    const LEFT_EYE_RIGHT_CORNER = 'LEFT_EYE_RIGHT_CORNER';
    const LEFT_EYE_BOTTOM_BOUNDARY = 'LEFT_EYE_BOTTOM_BOUNDARY';
    const LEFT_EYE_LEFT_CORNER = 'LEFT_EYE_LEFT_CORNER';
    const RIGHT_EYE_TOP_BOUNDARY = 'RIGHT_EYE_TOP_BOUNDARY';
    const RIGHT_EYE_RIGHT_CORNER = 'RIGHT_EYE_RIGHT_CORNER';
    const RIGHT_EYE_BOTTOM_BOUNDARY = 'RIGHT_EYE_BOTTOM_BOUNDARY';
    const RIGHT_EYE_LEFT_CORNER = 'RIGHT_EYE_LEFT_CORNER';
    const LEFT_EYEBROW_UPPER_MIDPOINT = 'LEFT_EYEBROW_UPPER_MIDPOINT';
    const RIGHT_EYEBROW_UPPER_MIDPOINT = 'RIGHT_EYEBROW_UPPER_MIDPOINT';
    const LEFT_EAR_TRAGION = 'LEFT_EAR_TRAGION';
    const RIGHT_EAR_TRAGION = 'RIGHT_EAR_TRAGION';
    const LEFT_EYE_PUPIL = 'LEFT_EYE_PUPIL';
    const RIGHT_EYE_PUPIL = 'RIGHT_EYE_PUPIL';
    const FOREHEAD_GLABELLA = 'FOREHEAD_GLABELLA';
    const CHIN_GNATHION = 'CHIN_GNATHION';
    const CHIN_LEFT_GONION = 'CHIN_LEFT_GONION';
    const CHIN_RIGHT_GONION = 'CHIN_RIGHT_GONION';
}
